### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by GriffinMartin** [GriffinMartin/MI-449-SS17-740-js-server-intro-jtrO3q#1]
@chrisvfritz Can you take a look at this? It's [hosted here](https://mart1444-js-server-intro.herokuapp.com/) and meets the following criteria:

- [x] At every URL, you respond with HTML, starting with an `h1` element (though for this project, it doesn't have to be a complete HTML page)
- [x] When a user visits `/`, they see a greeting
- [x] When a user visits `/random-joke`, they see one of at least three [knock-knock jokes](http://www.short-funny.com/best-knock-jokes.php) (`Math.random()` may be useful 😉)
- [x] When a user visits `/cuteness`, they see a picture of a cute animal (I'm sure you can find one on the Internet 😛)
- [x] At every other URL, display an error page (if you want to make it funny, see [these examples](http://www.hongkiat.com/blog/60-really-cool-and-creative-error-404-pages/) for inspiration)
- [x] The error page includes the requested URL, similar to [Google's error page](http://google.com/secret-plan-to-take-over-the-world)
- [x] Every page that is _not_ the homepage (`/`) contains a link to it

**Comment by chrisvfritz** [comment]
Looking great! 

- I doubt anyone will be able to match the cuteness of those baby sloths 😍
- Nice images for the joke punchlines 🍪
- Excellent little detail that the link to the error page generates a different URL on each page load 🤓

Beyond the `h2`s not technically being valid in this case, which I'll let slide for this one 🙂, the only room for improvement I see is that the variable declarations are missing `var`. This make them global rather than scoped to the function (we'll learn more about variable scope in a lesson probably being released in the next week). For now though, general rule is _always_ use `var`, or else you can encounter weird side effects.

**Comment by GriffinMartin** [comment]
@chrisvfritz I fixed up the missing `var` . My linter wasn't working so I never caught my mistake!

**Comment by chrisvfritz** [comment]
Looks great! :shipit: 🎉 🚀 🔥 Try checking for more updates in Atom and seeing if the linter is fixed now. I know it was having some issues last night, but I think they should be fixed in the latest updates. 🙂 

As the first person to complete this lesson, were there any hiccups or other issues you encountered. Any recommendations?

**Comment by GriffinMartin** [comment]
@chrisvfritz no hiccups that I can remember. As far as recommendations maybe have there be more requirements. Compared to the last couple projects this one took a lot less time to complete.

**Comment by chrisvfritz** [comment]
Ha, that's exactly what we were going for actually! Server-side stuff is a completely new thing for a lot of people to wrap their minds around, so we wanted to err on the side of a gentler introduction. 😄
